### ISSUE TITLE
configure Tailwindcss to website

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#1]
We decide to use Tailwind.  It's a HTML website.
We love to add tailwindcss cz tailwind made easy.

For guidelines: [visit](https://themesberg.com/knowledge-center/tailwind-css/html)

> Even if you are a beginner, i would love to hear that you wanna try.

**Do not add tailwindcss cdn or link, you have to install it via npm and link to html file**

**Comment by lewisushindi** [comment]
i can work on this

**Comment by devvsakib** [comment]
i will check your pr now

**Comment by devvsakib** [comment]
please check my comment @lewisushindi

**Comment by lewisushindi** [comment]
@devvsakib  done adding the .gitignore file and included the node_modules file

**Comment by devvsakib** [comment]
Done #5
