### ISSUE TITLE
Fatal [BUG]: I cant run the repo 

### ISSUE THREAD

**Issue by MohamedAlDeep** [devvsakib/github-error-solve#102]
**Describe the bug**
There is no file that has vite because what i think there is no `github-error-solve` folder so i cant run the repo 

**To Reproduce**
1. `npm run dev`

**Expected behavior**
`vite is not recognized`

**Screenshots**
![image](https://user-images.githubusercontent.com/95958815/214536589-9153e06b-e4f5-4c24-9a7b-ef018d3fbc5a.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [N/A]
 - Version [N/A]

**Additional context**
N/A

**Comment by MohamedAlDeep** [comment]
Which folder should i `cd` to?
![image](https://user-images.githubusercontent.com/95958815/214540447-6b42b584-73e7-4148-b99a-2535af50bda4.png)

**Comment by MohamedAlDeep** [comment]
@devvsakib

**Comment by devvsakib** [comment]
please run `npm i` first, you have to install the dependency first. then run `npm run dev`

there are a file name `vite.config.js` at the very bottom.

**Comment by MohamedAlDeep** [comment]
Noice
