### ISSUE TITLE
add image to readme 

### ISSUE THREAD

**Issue by Hrishi5111998** [devvsakib/github-error-solve#107]
**Is your feature request related to a problem? Please describe.**
image is not been able to in the readme section! please add image

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![2023-01-26 (1)](https://user-images.githubusercontent.com/115489262/214882913-31e75894-901d-4229-b6b7-44437f66b71f.png)

**Comment by hirentimbadiya** [comment]
i can work on this issue can anyone assign me?

**Comment by devvsakib** [comment]
Assigned @hirentimbadiya

**Comment by MohamedAlDeep** [comment]
Wassup this issue didn't change for mobile here is a screenshot shot![Screenshot_20230228_211138.jpg](https://user-images.githubusercontent.com/95958815/221955433-46d0ef6a-32ad-412b-8f74-ff3e09cc3837.jpg)

**Comment by devvsakib** [comment]
Hi @hirentimbadiya  how's going?

**Comment by MohamedAlDeep** [comment]
Can you assign me @devvsakib

**Comment by hirentimbadiya** [comment]
I was busy with my college work , I will do it this week.

**Comment by devvsakib** [comment]
I think @MohamedAlDeep  can do it now, so I'm assigning to him

**Comment by devvsakib** [comment]
Completed #127
