### ISSUE TITLE
enhancement of error card animation

### ISSUE THREAD

**Issue by safil-badarudeen** [devvsakib/github-error-solve#108]
i have added transition to error card so when ever hover happens it will increase size it looks good, what do you think can i make a pull request for that .

**Comment by devvsakib** [comment]
sure make pr

**Comment by safil-badarudeen** [comment]
![image](https://user-images.githubusercontent.com/111175419/215166756-c58d6344-90b5-42e5-b668-3240c28b39a4.png)


getting this error , is it a local problem , deleted and cloned repo again after syncing the branch, do you get this errror, because this animation is not loading in  website , i think so

**Comment by devvsakib** [comment]
@safil-badarudeen  you can solve this error. just find the image tag in the code, then change src `/public/assets/` to `/assets/`

**Comment by safil-badarudeen** [comment]
![image](https://user-images.githubusercontent.com/111175419/215241344-8b626b89-ee51-4d8d-99e2-ff4e34b08eab.png)


eventhough after adding /assets in header image tag still this one error remains, other solved.
I think this one is from any of configuration,

**Comment by devvsakib** [comment]
Completed #109
