### ISSUE TITLE
Pull Type Issue

### ISSUE THREAD

**Issue by mohd-raza** [devvsakib/github-error-solve#111]
**Is your feature request related to a problem? Please describe.**
"error: failed to push some refs to '[https://github.com/…](https://github.com/%E2%80%A6)'": This error occurs when you try to push to a repository but your local branch is behind the remote branch and you need to pull the changes first.

**Describe the solution you'd like**
git fetch origin
git status
git merge origin/remote-branch-name
git push origin BRANCHNAME

**Comment by mohd-raza** [comment]
@devvsakib Hey Brother, Can you please this issue to me please!!

**Comment by devvsakib** [comment]
assgined @mohd-raza

**Comment by mohd-raza** [comment]
@devvsakib hey sakib, I have made a PR, please check it out. Thanks!!

**Comment by devvsakib** [comment]
Completed #112
