### ISSUE TITLE
add animation to filter menu

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#128]
When the User clicks the filter, it comes with animation, but if the user clicks again to hide, it disappears instantly.
![image](https://user-images.githubusercontent.com/88339569/223176547-3e9e4d5b-b974-4b6c-b345-c0ea6e6bfd27.png)

Add ease-out animation. you can use any type of animation package.

**Comment by akashIsCoding** [comment]
Hey @devvsakib , would love to work on this issue, please assign it to me

**Comment by devvsakib** [comment]
All yours @akashIsCoding
