### ISSUE TITLE
add GIT cmd to json file

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#137]
Add git command

Example:
```json
    {
      "type": "cmd",
      "title": "How to remove a Local branch",
      "description": "If you want to remove a Local branch, you can use this command. It will remove the branch you want to remove.",
      "solutions": "git branch --delete branch_name"
    }
````

file path: `src/data/error.json`

Note: < less than sign use to break line in json file. Using < will break your line
example:
```json
    {
      "solutions": "git < branch --delete <branch_name"
    }
````
output: 
```
git
branch --delete 
branch_name
```
Use < if you have multiple command

Before PR, add your details in the contributors' file too.

> PR will be not merged if contributors details not added

**Comment by PiseAtharva** [comment]
Hey Sakib, loved the project, I was wondering if i can start off with this Issue ?

**Comment by devvsakib** [comment]
Sure @

**Comment by devvsakib** [comment]
sure @PiseAtharva

**Comment by devvsakib** [comment]
Merged #148 

PR: @PiseAtharva

**Comment by TheLoneAlchemist** [comment]
Hey I Like you project and want resolve this. Can you assign me it.

**Comment by devvsakib** [comment]
Assigned @TheLoneAlchemist

**Comment by Bharadwajshivam28** [comment]
@devvsakib If anyone is not Working then can i can go with it??

**Comment by TheLoneAlchemist** [comment]
> Assigned @TheLoneAlchemist

Kindly Check my new PR
