### ISSUE TITLE
change the link to live website

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#14]
Currently, GES link is not working, please change this link to https://github-error-solve.vercel.app and get your GREEN SQUARE
![image](https://user-images.githubusercontent.com/88339569/211529624-562f0c51-e10d-4cc2-92e1-91ba3c27b9a6.png)

**Comment by BoltUltra** [comment]
Hi, I would like to work on this

**Comment by devvsakib** [comment]
assigned @BoltUltra

**Comment by devvsakib** [comment]
fixes #21
