### ISSUE TITLE
Add copy button/icon next to the solution commands

### ISSUE THREAD

**Issue by Ngoakor12** [devvsakib/github-error-solve#143]
**Is your feature request related to a problem? Please describe.**
Not a big issue, but copying commands by highlighting is sometimes tiring

**Describe the solution you'd like**
Add a copy button/icon next to the oneliner solutions for easy copy. For the solutions that require multiple commands, I'm not sure...may a copy icon on each line of the solution?

**Describe alternatives you've considered**

**Additional context**
Again, love the project. This is just a harmless little suggestion. I understand that It might mean the ui is more crowded on the multi command solutions if they all have a copy button/icon

**Comment by imlakshaychauhan** [comment]
Hey, 
I can't file the card component of the home page, I wanted to add copy button to it for copying.

**Comment by imlakshaychauhan** [comment]
Hey, I've added copy button to it
#145
please review and merge it

**Comment by devvsakib** [comment]
I reviewed your PR @imlakshaychauhan . Please check my comment🔃

**Comment by devvsakib** [comment]
Completed by #145
