### ISSUE TITLE
add link to footer

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#146]
**Is your feature request related to a problem? Please describe.**
Add this link to the footer -> https://github.com/PowerTheWeb
![image](https://user-images.githubusercontent.com/88339569/224552387-7113e726-f7ba-42ed-9d90-9dc93842989c.png)

**Additional context**
If you want to join this community please let me know.

**Comment by dialejo24** [comment]
i would like to solve this issue. can i solve it by enclosing "PTW Community" in an anchor tag ?

**Comment by devvsakib** [comment]
Yes, @dialejo24
