### ISSUE TITLE
[FEAT]: add animation to card when scroll down or vissible

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#156]
**Is your feature request related to a problem? Please describe.**
Add animation to card when scroll or visible
![image](https://user-images.githubusercontent.com/88339569/226643076-3a10b1f6-3ffe-439f-a301-1a7ba9c305de.png)

**Describe the solution you'd like**
You have to use frammer-motion for the animation

**Additional context**
Join discord for any [help](https://discord.gg/xwRbDwnbMr)

**Comment by devvsakib** [comment]
of course @karthiknadar1204

**Comment by karthiknadar1204** [comment]
@devvsakib ,so sorry for not updating,will update the pr by tomorrow evening

**Comment by karthiknadar1204** [comment]
@devvsakib ,i have added animated motion to the button "Read more",when you hover,it will have an rising effect.adding similar effect to the card as well

**Comment by karthiknadar1204** [comment]
Have added a hover effect  to the buttons as well as the cards in the blog page cards using framer motion,will initiate the pr

**Comment by karthiknadar1204** [comment]
i am so sorry @devvsakib , github-error-solve it was,i worked on the wrong repository,i added the effects on the powertheweb repo,will correct this asap.

Completely my mistake.

**Comment by karthiknadar1204** [comment]
Will add the changes tomorrow at the same time,Extremely sorry for the inconvenience caused.

**Comment by karthiknadar1204** [comment]
@devvsakib ,will update all the issues over the weekend

**Comment by karthiknadar1204** [comment]
@devvsakib ,i have explored the code base,what kind of animations do you want,the existing effects include a hover effect on the cards and well as the "Solution" button.

**Comment by Mudit-Jxin7** [comment]
hey if this issue is open and someone is not working on it , Can I?
