### ISSUE TITLE
[BUG]: FilterType menu ease-in-out animation 

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#157]
The mobile filter menu animation not working properly. When the user clicks the filter type, it comes with awesome animation but dismisses instantly.
![image](https://user-images.githubusercontent.com/88339569/226644242-ef6a5568-458e-4726-a92f-64892d605cc2.png)

**To Reproduce**
Add ease-out animation

**Expected behavior**
Should ease-out smoothly

**Screenshots**
added

**Comment by abhinav2712** [comment]
@devvsakib Assign me this issue, will get it done in a min

**Comment by devvsakib** [comment]
Of course🔥 all your's @abhinav2712

**Comment by abhinav2712** [comment]
@devvsakib Hey, I went through the whole files structure  and found the file which targets the search bar which has categories of the errors. I am trying to change the file "SearchInput.jsx" file on my local but none of the changes are being reflected. 
I tried changing "filter by type" to just "filter" just to check if my target file is correct but it doesnt change anything,
Do give me a heads up for this one..

**Comment by abhinav2712** [comment]
@devvsakib I refreshed my localhost, still its same, Look I changed the spellings still :/
<img width="641" alt="image" src="https://user-images.githubusercontent.com/68495520/227398373-c8aee6a6-5614-4095-93d4-e87a099ec261.png">

heres the output:

![image](https://user-images.githubusercontent.com/68495520/227398463-a8a0b2e2-0e34-4018-b3eb-471eb752b902.png)

Do you have any idea on why this is happening?

**Comment by devvsakib** [comment]
I didn't get your point. what do you mean? @abhinav2712

**Comment by abhinav2712** [comment]
@devvsakib As u can see I have changes the names in nav items, still the changes aren't being reflected, (even after restarting localhost) Can you confirm if I am making changes in the correct file for not?

**Comment by devvsakib** [comment]
this nav is for mobile. 
![image](https://user-images.githubusercontent.com/88339569/227495813-e600b8ad-c04a-4113-86cb-27eb77c7488d.png)

**Comment by abhinav2712** [comment]
@devvsakib does that 

> this nav is for mobile. ![image](https://user-images.githubusercontent.com/88339569/227495813-e600b8ad-c04a-4113-86cb-27eb77c7488d.png)

is that file somewhere else?

**Comment by devvsakib** [comment]
@ezequielbugnon yes, you are right

**Comment by devvsakib** [comment]
Completed #163
