### ISSUE TITLE
add new error  with solution

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#167]
Hi there OS people, I saw that people often face this error
![image](https://github.com/devvsakib/github-error-solve/assets/88339569/d802b589-bbae-4bb4-a5cf-3020de585886)

please add this error in the error json file
 template: 
```json
 {
      "type": "push",
      "title": "Your branch is ahead of ",
      "description": "Some quick example text to build on the card title and make up the bulk of the card's content.error: failed to push some refs to 'git@github.com:/reponame.git' To prevent you from losing history, non-fast-forward updates were rejected Merge the remote changes (e.g. 'git pull') before pushing again. See the 'Note about fast-forwards' section of 'git push --help' for details.",
      "solutions": "git pull<git push origin [branch name]"
    },
```

thank you people, happy OS

**Comment by aAYUSHkujur** [comment]
Hi @devvsakib, I have created a new PR. Please feel free to review it. Thank You.

**Comment by aarpardev** [comment]
Hello, @devvsakib I just made a new Pull Request. Please let me know if there's anything else I need to do after doing a review. Thank you.

**Comment by ashutosh887** [comment]
Please close this issue I can see it's merged
