### ISSUE TITLE
Mispositioning of Error message

### ISSUE THREAD

**Issue by shobhitexe** [devvsakib/github-error-solve#169]
**Describe the bug**
As we can see on Attached SS the error message appears on left side whereas i guess it will look good if it come at center
**To Reproduce**
1. Go to 'https://github-error-solve.vercel.app/'
2. Click on 'Search'
3. Type 

**Screenshots**
![image](https://github.com/devvsakib/github-error-solve/assets/29349136/b453eb2d-89bc-467a-b40e-da4e786a0b74)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Chrome
 - Version 114.0.5735.110 (Official Build) (64-bit)

**Comment by devvsakib** [comment]
Awesome, Do you want to do this?

**Comment by shobhitexe** [comment]
> Awesome, Do you want to do this?

Yes sure!
