### ISSUE TITLE
Improve error card desgin

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#174]
**Is your feature request related to a problem? Please describe.**
We have to improve error card in our site

**Describe the solution you'd like**
Please comment below what is your suggestions

**Comment by bishwobista** [comment]
maybe change the color of the error text or error title

**Comment by HarshMakadiya** [comment]
@devvsakib Can you assign me to this issue? I would like to work on it.

**Comment by Rehan52004** [comment]
I want to work on it, please assign me this issue.

**Comment by Abishkardhenga** [comment]
hey @devvsakib   shall i work on this issue
