### ISSUE TITLE
hide popup if user click outside of popup

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#175]
**Describe the solution you'd like**
Close popup when user click outside
![image](https://github.com/devvsakib/github-error-solve/assets/88339569/f463ad02-e01a-48d7-8ed3-7ba8f6513898)

**Additional context**
Adding animation on popup o/c will be apprieciete

**Comment by A-Kashif108** [comment]
i would like to work on this issue, can you please assign me ?

**Comment by devvsakib** [comment]
sure @A-Kashif108
