### ISSUE TITLE
implement Light Mode 

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#177]
**Is your feature request related to a problem? Please describe.**
Implement light mode

**Describe the solution you'd like**
While implementing light/dark mode, also make sure the theme matches with the user device theme. Suppose if user uses dark mode, the website should be i dark theme by default

**Describe alternatives you've considered**
Complete this task to get Hacktoberfest to accept

**Additional context**
Additional improvements are highly appriciete

**Comment by devXprite** [comment]
Hii @devvsakib , I want to work on this issue.

**Comment by devvsakib** [comment]
> Hii @devvsakib , I want to work on this issue.

Go Ahead

**Comment by yashwanthvarma18** [comment]
Hello @devvsakib  , I'm eager to contribute. Please assign me
