### ISSUE TITLE
[SUGGESTION]: give suggestion to improve the site

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#180]
**Is your feature request related to a problem? Please describe.**
We are trying to improve our site, Please share your thought.

**Describe the solution you'd like**
Any suggestion appriciete

**Comment by ShrutiKolla** [comment]
@devvsakib I want to take a look at at. Can i fork it?

**Comment by devvsakib** [comment]
> @devvsakib I want to take a look at at. Can i fork it?

Sure, did you forked yet?
