### ISSUE TITLE
[FEAT]: add hamburger menu for small device

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#181]
**Is your feature request related to a problem? Please describe.**
RN, our menu is not mobile responsive.

**Describe the solution you'd like**
Make it mobile responsive, add a bar icon and add animation on menu open/close. 
** Maybe we can use breakpoint `<= 992px`

![image](https://github.com/devvsakib/github-error-solve/assets/88339569/fafbe303-5dcd-43ed-b86c-b0d50dda57ba)

**Comment by gandholi-kumar** [comment]
Hi @devvsakib 
I would like to work on this bug, can you kindly assign it to me. 

**Queries:** 
- Was this application hosted on any platform? 
- If you could provide a prototype(or a reference) of the requirement that would really help me in better understanding.

**Comment by devvsakib** [comment]
> Hi @devvsakib I would like to work on this bug, can you kindly assign it to me.
> 
> **Queries:**
> 
>     * Was this application hosted on any platform?
> 
>     * If you could provide a prototype(or a reference) of the requirement that would really help me in better understanding.

no ref needed, just a simple mobile menu.  just clone this project and run on your local and make PR.

**Comment by gandholi-kumar** [comment]
Hi @devvsakib 
Awaiting for your approval of my merge request.
