### ISSUE TITLE
reduce font weight

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#182]
![image](https://github.com/devvsakib/github-error-solve/assets/88339569/26e565fa-652c-428c-a49e-1bdb137fc592)

reduce font weight to normal. (400/500)

**Comment by Yash282003** [comment]
@devvsakib I would like to work on this issue. Can you please assign it to me?

**Comment by devvsakib** [comment]
Sure @Yash282003

**Comment by wajaht-ali** [comment]
Hey @devvsakib , I am interested in solving the issue. Could you please assign it to me?

**Comment by harshsinghcs** [comment]
Hello @devvsakib! I'm eager to tackle this issue and contribute to the project. Please assign it to me, and let's work together to make a positive impact. 💻🚀
