### ISSUE TITLE
add highlighte/active status to tag when user filter.

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#188]
Make filtered tag active, something like a border or shadow in the tag

![image](https://github.com/user-attachments/assets/6041b8b8-56ec-4f53-ba10-6542cee2810d)

in pic, I have selected PULL tag, so this tag should be highlighted.
![image](https://github.com/user-attachments/assets/ef74c942-8cf3-4703-874c-b818275547ea)

**Comment by MohitKambli** [comment]
Hello,
Hope you're doing well.
Could I possibly work on this issue?

Thanks and Regards,
Mohit Kambli

**Comment by MohitKambli** [comment]
Hello,
On incorporating the necessary code changes, I have added a red border to the selected tag.
This is how it is looking as of now:
1) 
![image](https://github.com/user-attachments/assets/3a5fa651-a9b8-4dfa-8bcc-46721ea6f323)

2) 
![image](https://github.com/user-attachments/assets/88f88690-7e1a-452d-b48d-22e0e47dfdac)

If at all this looks fine to you, then do let me know.
I will raise a PR for the same.
Sincere apologies if I misunderstood something or implemented anything that seems to be incorrect.
Thank you so much for understanding.

Regards,
Mohit Kambli

**Comment by devvsakib** [comment]
Sure, raise a PR. @MohitKambli
