### ISSUE TITLE
improve DOC page

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#189]
RN, the doc page is not looking good and readability is bad. improve the page with good readability and we should create separate pages for every doc.
![image](https://github.com/user-attachments/assets/73f45c45-6361-4b23-bc51-d43bb54d4eff)

**Comment by Apocalypse96** [comment]
I would love to solve this issue @devvsakib pls assign it to me

**Comment by devvsakib** [comment]
Sure @Apocalypse96

**Comment by Apocalypse96** [comment]
But creating new pages for each doc would be unoptimal like is there a serious need for that the compact version looks good

**Comment by PATILYASHH** [comment]
I'd like to take on this task of improving the documentation page. I will create separate dynamic pages with dynamic URLs for each document, as suggested. I'll ensure the documentation is easier to navigate and more readable.

**Comment by Gokilp** [comment]
assign to me

**Comment by Gokilp** [comment]
Thank you

**Comment by Gokilp** [comment]
can you explain clearly about the issue

**Comment by devvsakib** [comment]
Are you still working? @Gokilp

**Comment by devvsakib** [comment]
checkout my PR. @Gokilp

**Comment by devvsakib** [comment]
list
![image](https://github.com/user-attachments/assets/ad765cf0-71c4-43f8-989b-dee68bdb9ce0)

single page for document
![image](https://github.com/user-attachments/assets/ad765cf0-71c4-43f8-989b-dee68bdb9ce0)
