### ISSUE TITLE
Add Favicon to website 

### ISSUE THREAD

**Issue by PATILYASHH** [devvsakib/github-error-solve#191]
**Favicon** The logo displayed on the actual web page, often at the top of the site and typically within the header, is usually just referred to as the  ***website logo.***

For example - ![Screenshot_2024_0725_073726.jpg](https://github.com/user-attachments/assets/ac2b1b32-e655-40a4-a4e6-8a0e81e861b7)

Here we can see the Github logo like that.

**Comment by PATILYASHH** [comment]
Assign me I can do this

**Comment by PATILYASHH** [comment]
> Author

https://github.com/devvsakib/github-error-solve/pull/192

i fixed this issue

**Comment by devvsakib** [comment]
Completed #193
