### ISSUE TITLE
[SUGGESTION] UI/UX design improvement

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#20]
We have built the basic structure of GES. Now we need some suggestions for UI/UX design improvements. Please drop any suggestions you have. 

- Background Color
- Header BG Color
- Card BG Color
- Font Family
- Layout
- Anything we need to add?

rn our website:
![image](https://user-images.githubusercontent.com/88339569/211566893-70229c9c-4a6f-4dc4-bb82-2f8f30cbe1a1.png)

You can contribute and get Green Square🟩

**Comment by ankitk26** [comment]
Hi @devvsakib, I have suggested a design for the application in the image below. You may take some points which you can implement in your application.
* Font used - Fira Mono
* Colors used - #F4F7F5, #A7A2A9, #858AE3, #1E1E1F, #28282A. Other colours are same as the original design.
* I used the icons from Material Icons.

![image](https://user-images.githubusercontent.com/53444460/211662068-f4ec3c3d-2cf4-49e7-9d69-bfde6a0d7bf9.png)

**Comment by devvsakib** [comment]
wow, thats look amazing, do you want to work on this? @ankitk26 

thank you so much for the suggestions

**Comment by codemeop** [comment]
> Hi @devvsakib, I have suggested a design for the application in the image below. You may take some points which you can implement in your application.
> 
>     * Font used - Fira Mono
> 
>     * Colors used - #F4F7F5, #A7A2A9, #858AE3, #1E1E1F, #28282A. Other colours are same as the original design.
> 
>     * I used the icons from Material Icons.
> 
> 
> ![image](https://user-images.githubusercontent.com/53444460/211662068-f4ec3c3d-2cf4-49e7-9d69-bfde6a0d7bf9.png)

this looks fantastic, i think we can use a gradient background color? just asking

**Comment by ankitk26** [comment]
> wow, thats look amazing, do you want to work on this? @ankitk26
> 
> thank you so much for the suggestions

Thank you @devvsakib for the appreciation. I would like to contribute to this project.

**Comment by ankitk26** [comment]
> > Hi @devvsakib, I have suggested a design for the application in the image below. You may take some points which you can implement in your application.
> > ```
> > * Font used - Fira Mono
> > 
> > * Colors used - #F4F7F5, #A7A2A9, #858AE3, #1E1E1F, #28282A. Other colours are same as the original design.
> > 
> > * I used the icons from Material Icons.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/53444460/211662068-f4ec3c3d-2cf4-49e7-9d69-bfde6a0d7bf9.png)
> 
> this looks fantastic, i think we can use a gradient background color? just asking

Thank you @codemeop. We can use a suitable gradient if it looks good

**Comment by devvsakib** [comment]
@ankitk26  thank yo, assigned

**Comment by devvsakib** [comment]
thanks for the suggestions @codemeop

**Comment by ankitk26** [comment]
@devvsakib, for the styles, should I completely write in Tailwind or keep the simple classes defined?

**Comment by devvsakib** [comment]
try to focus on tailwind, and you can define classes if you want @ankitk26

**Comment by devvsakib** [comment]
done by #35
