### ISSUE TITLE
name convension for resources title

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#238]
title should be Tools Libraries, Learning Resources so on.
![image](https://github.com/user-attachments/assets/cdc9220b-52b3-4577-8d25-a0decb5091aa)

> Tips:
> replace(/([a-z])([A-Z])/g, '$1 $2')

**Comment by nishad0011** [comment]
Hey! Can I attempt to solve this issue?

**Comment by devvsakib** [comment]
of course, @nishad0011

**Comment by devvsakib** [comment]
let me know if you want help !! @nishad0011
