### ISSUE TITLE
add error to error.json file

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#26]
if you get any errors and solved or not, please add them to `src/data/error.json` file.
We are collecting all types of errors that may occur when you commit, push, pull, merge, or while changing branches.

Example:
```json
 {
      "type": "push",
      "title": "! [rejected] branch -> branch (non-fast-forward)",
      "description": "Some quick example text to build on the card title and make up the bulk of the card's content.error: failed to push some refs to 'git@github.com:/reponame.git' To prevent you from losing history, non-fast-forward updates were rejected Merge the remote changes (e.g. 'git pull') before pushing again. See the 'Note about fast-forwards' section of 'git push --help' for details.",
      "solutions": "git push origin [branch name] -f"
    }
```

Type: add, pull, merge, push, commit, git init, etc...
Title: it's mandatory to add a title CZ our search filter work on the title.
Description: Copy the error from the terminal or describe it
Solution: If you know how to solve it, please add it here. to break the link use < this. if not solved leave it blank.

**Comment by AryanGodara** [comment]
I'll get started with this, please assign me to this issue @devvsakib !

**Comment by devvsakib** [comment]
sure thing, good luck @AryanGodara

**Comment by devvsakib** [comment]
Hi, @AryanGodara  how's going

**Comment by AryanGodara** [comment]
Sorry @devvsakib, I got tangled in college work, I'll start work on this this weekend.
Sorry for the inactivity!

**Comment by devvsakib** [comment]
@AryanGodara  no problem, take your time
