### ISSUE TITLE
instead using text logo, we can use and logo png

### ISSUE THREAD

**Issue by codemeop** [devvsakib/github-error-solve#28]
we can use png logo instead text logo
![image](https://user-images.githubusercontent.com/110708883/211734638-73e25666-82eb-4fa0-af24-14e6bb7303f2.png)

**Comment by codemeop** [comment]
@lewisushindi  i mean we can design a logo like this. 
![image](https://user-images.githubusercontent.com/110708883/211802830-54453360-a2e4-4194-8da2-1aea0210f8db.png)

**Comment by lewisushindi** [comment]
@codemeop  yeah thats a great idea

**Comment by devvsakib** [comment]
tbh, I was thinking the same. we better use a logo instead of this text. but i have no idea about logo design. @lewisushindi 

thanks for bringing up the idea @codemeop

**Comment by codemeop** [comment]
any suggestions?
