### ISSUE TITLE
change title color when search query match

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#3]
RN, we have a search input. we want to change the title color when user find their error
![image](https://user-images.githubusercontent.com/88339569/211145572-ef9bce34-bfee-4e66-bf88-e24ef82f7aa8.png)

change color to #0D6EFD
![image](https://user-images.githubusercontent.com/88339569/211145657-8bf9a668-695a-40c5-9070-1081a7dcda4e.png)

when input value clear, make sure to remove color

**Comment by lewisushindi** [comment]
I can work on this

**Comment by devvsakib** [comment]
Assigned @lewisushindi
