### ISSUE TITLE
[DOCS]: add a DOCs page in the menu

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#37]
create a folder name `pages` then add doc.jsx page. and add a link to the menu. no need to add react-router. just add it
![image](https://user-images.githubusercontent.com/88339569/212035088-4822c90f-165b-4cfc-b897-dbf0ccb65547.png)

**Comment by nawarajshah** [comment]
can you assign this issue to me

**Comment by devvsakib** [comment]
@nawarajshah  go ahead , all yours

**Comment by nawarajshah** [comment]
is it ok to write just "doc" or you want me to add icon along with it?

**Comment by devvsakib** [comment]
you can try it, if its look better with icon, then ok @nawarajshah

**Comment by nawarajshah** [comment]
@devvsakib can you make me clear, you said "add a link to the menu" but do not use react-router. but the Link tag comes with react-router-dom, so do you want me to put just a doc on the menu?
is this ok?
![image](https://user-images.githubusercontent.com/11453784/212344572-4c103d02-1617-419c-97d1-4dbf9c71d42c.png)

**Comment by devvsakib** [comment]
okkk do this. please make sure both are on the right side. you are doing great
![image](https://user-images.githubusercontent.com/88339569/212345412-8affc0f1-5fa8-48ed-8270-2188f7748d1f.png)

**Comment by nawarajshah** [comment]
done
![Screenshot (19)](https://user-images.githubusercontent.com/11453784/212345818-be6ce5ec-b918-4edf-9b34-dddfe932931c.png)

**Comment by devvsakib** [comment]
looks great.

**Comment by nawarajshah** [comment]
if its fine then can i make a push request? or I have to do other things also?

**Comment by devvsakib** [comment]
you can make pr, but if you want to improve something that you want, it's all up to you

**Comment by nawarajshah** [comment]
i have made pr

**Comment by nawarajshah** [comment]
thank you for your help

**Comment by devvsakib** [comment]
Closed #44

**Comment by devvsakib** [comment]
@nawarajshah thanks for contributing, you can star the repo, highly appreciate
