### ISSUE TITLE
change grid layout

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#38]
make 3column for large device
![image](https://user-images.githubusercontent.com/88339569/212035421-1dcdcb21-04a0-42f0-a4d3-b511992ced78.png)

make 2column for medium device
![image](https://user-images.githubusercontent.com/88339569/212035537-fd9e4587-2dea-4fd3-b9fb-20d3cfa19804.png)

**Comment by imtiazpy** [comment]
This issue seems unassigned, can I take it? I am willing to work on it.

**Comment by devvsakib** [comment]
@imtiazpy  suree. thanks for contributing

**Comment by devvsakib** [comment]
@imtiazpy  thank you, your pr merged, don't forget to leave a star⭐

**Comment by devvsakib** [comment]
Closed #48

**Comment by imtiazpy** [comment]
Glad to contribute. there's another issue I think that needs to be worked on. When the solution button from any card gets clicked it expends that card along all the cards in it's row. It would look good if only the card the button is clicked on gets expended. Or there can be a modal for showing the solution.

**Comment by devvsakib** [comment]
@imtiazpy  sure you can raise an issue and start working on it🎊🎊
