### ISSUE TITLE
design the Filter button

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#39]
currently we dont have any design for this button. dont be confused, its a button though. design something you like
![image](https://user-images.githubusercontent.com/88339569/212035899-608a372e-4653-41a8-8575-47d25ccf1f29.png)

**Comment by lewisushindi** [comment]
Button color preference?

**Comment by devvsakib** [comment]
white bg black text? @lewisushindi

**Comment by devvsakib** [comment]
want to take this? @lewisushindi

**Comment by anvikshik** [comment]
Hey, I would like to take this one, if that's okay with you.

**Comment by devvsakib** [comment]
@anvikshik  go ahead, all yours

**Comment by devvsakib** [comment]
Closed #42
