### ISSUE TITLE
add transitions to filter button

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#40]
add a transition to the button. when clicking its shows the menu instantly. add some delay to it
![image](https://user-images.githubusercontent.com/88339569/212036250-6c92a54e-c683-488c-8646-9dbe8197b1ed.png)

![image](https://user-images.githubusercontent.com/88339569/212036160-fcfe5051-1c3a-4cd9-9a16-b6eebfaba5e7.png)

**Comment by hussain-shariff** [comment]
Hey would like to work on this!

**Comment by devvsakib** [comment]
@hussain-shariff  go ahead, all yours

**Comment by hussain-shariff** [comment]
@devvsakib will a delay of 0.5 sec be fine?

**Comment by devvsakib** [comment]
use according to you @hussain-shariff

**Comment by hussain-shariff** [comment]
@devvsakib done!

**Comment by devvsakib** [comment]
please check my comment @hussain-shariff

**Comment by devvsakib** [comment]
Closed #41

**Comment by devvsakib** [comment]
thanks for contributing, you can leave a star  to the repository⭐

**Comment by hussain-shariff** [comment]
> thanks for contributing, you can leave a star to the repository⭐

glad I could contribute.
