### ISSUE TITLE
[FEAT]: add dummy content to doc page

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#46]
we have a doc page but the page is empty and not linked. file dir `src/pages/doc.jsx`
add some dummy text and title to the page.
![image](https://user-images.githubusercontent.com/88339569/212350522-93700d8d-e9bc-450f-8e04-29ac814de5f7.png)

design concept:
![image](https://user-images.githubusercontent.com/88339569/212351308-73c5ac2b-19f4-4179-8e80-c751e3645687.png)

first, you have to link the page.

**Comment by imtiazpy** [comment]
I would like to take on this issue. 
Assign me

**Comment by devvsakib** [comment]
@imtiazpy  sure

**Comment by imtiazpy** [comment]
I will start working on it after a couple of hours. Thank you for assigning me. @devvsakib

**Comment by imtiazpy** [comment]
@devvsakib , just a quick question - it seems like the project has no layout component. Should I create one? If I do, every other page we create later on will have the same header and footer in them.

**Comment by devvsakib** [comment]
wow, it would be great if you do that. @imtiazpy

**Comment by imtiazpy** [comment]
The task is completed. Please have look into it. @devvsakib 
Check the PR- https://github.com/devvsakib/github-error-solve/pull/49

**Comment by devvsakib** [comment]
merged, thank you so much for the effort. awesome stuff @imtiazpy

**Comment by devvsakib** [comment]
Closed #49
