### ISSUE TITLE
[Feature]: Make the Navbar fixed. 

### ISSUE THREAD

**Issue by imtiazpy** [devvsakib/github-error-solve#50]
As the user scrolls down, the navigation bar becomes obscured. In order to maintain easy access to the various pages on the website, including the homepage and documentation page, it is recommended that the navigation bar be fixed in place while scrolling. This will ensure that users can easily navigate between pages, even as they scroll through the website's content.

[GitHub-Error-Solve---Opensource-Projects.webm](https://user-images.githubusercontent.com/45868098/212622930-bb48800f-bbb4-4611-8060-00dd5ad98485.webm)

**Comment by devvsakib** [comment]
assigned @imtiazpy

**Comment by imtiazpy** [comment]
Okay I will start working on it.

**Comment by imtiazpy** [comment]
The is solved #53 
@devvsakib

**Comment by devvsakib** [comment]
Fixes #53
