### ISSUE TITLE
error on commit 

### ISSUE THREAD

**Issue by safil-badarudeen** [devvsakib/github-error-solve#51]
I found that there are no errors under the section of commit , can i add an error and solution that occur while commiting into error.json,  
![image](https://user-images.githubusercontent.com/111175419/212664039-f8a3e02b-9896-4a32-a5eb-75b0a9e168c4.png)

**Comment by devvsakib** [comment]
yes, bcz we dont have any error with commit. it would be great if you add some. thank you @safil-badarudeen

**Comment by safil-badarudeen** [comment]
data should be added only to error.json , right?

**Comment by devvsakib** [comment]
yes @safil-badarudeen

**Comment by devvsakib** [comment]
Fixes #54
