### ISSUE TITLE
[Bug]: Make the content sit inside the card

### ISSUE THREAD

**Issue by imtiazpy** [devvsakib/github-error-solve#52]
If Any title of a Github error get's bigger, it overflows out of the card.

Make the content of the card remain inside the card. 

It is happening because the height of the cards aligns with the height of other cards in the same row, making the content getting overflowed rather than wrapping into multiple lines. 

So the workaround would be to review the design again make the a consistent design

![GitHub Error Solve - Opensource Projects](https://user-images.githubusercontent.com/45868098/212626053-9c772817-b679-4b38-b1e9-c143a7bc11e0.png)

**Comment by devvsakib** [comment]
assigned to you @imtiazpy

**Comment by MohamedAlDeep** [comment]
Hello i did it,
Sorry if i didnt ask for assignment
(First time)

**Comment by devvsakib** [comment]
Closed as completed #72 
Thanks @MohamedAlDeep
