### ISSUE TITLE
readme update

### ISSUE THREAD

**Issue by safil-badarudeen** [devvsakib/github-error-solve#55]
I think read me should be made a little bit more beginner friendly by adding exact steps to follow while  they make changes locally , and how to create a  pull request . So even a beginner in web development can contribute with ease. we dont want to delete any data already in readme , but we can add bit more detail to it . Assign me if its good opinion to apply on readme.

**Comment by devvsakib** [comment]
sure thing, assigned @safil-badarudeen

**Comment by safil-badarudeen** [comment]
I have forked this repo for first contribution, If i want to contribute again , do i need to create a new fork from this repo?

**Comment by devvsakib** [comment]
@safil-badarudeen  nope, just click on the sync code. then open your terminal and run `git pull origin main`

**Comment by devvsakib** [comment]
here you will see Sync Fork, then update branch
![image](https://user-images.githubusercontent.com/88339569/213102791-4214e04a-8263-4498-ba8d-9435a27ee943.png)

**Comment by safil-badarudeen** [comment]
Thanks man. I will do this one asap.

**Comment by safil-badarudeen** [comment]
man, i was currently working on it , should i make a pull rerquest?

**Comment by devvsakib** [comment]
Im sorry, I thought its done, sorry @safil-badarudeen

**Comment by safil-badarudeen** [comment]
No i was working on this , for 2 days i was busy on a personal project.

**Comment by safil-badarudeen** [comment]
Made a pull after updation @devvsakib

**Comment by devvsakib** [comment]
closed as completed #78
