### ISSUE TITLE
[Fix]:  clear button should be visible only when the user types some text

### ISSUE THREAD

**Issue by hussain-shariff** [devvsakib/github-error-solve#56]
![Screenshot (178)](https://user-images.githubusercontent.com/118625304/212969720-219fe899-d1ac-4f69-8f84-645a65c368de.png)

Instead of having two clear buttons , one is enough and that should appear once the user starts typing in the search bar.

## would you like to work?
Yes I'm looking forward.

**Comment by hussain-shariff** [comment]
@devvsakib can you assign this to me?

**Comment by devvsakib** [comment]
sure @hussain-shariff

**Comment by devvsakib** [comment]
please check my comment #60  @hussain-shariff

**Comment by devvsakib** [comment]
Closed as Completed #60
