### ISSUE TITLE
Text error 

### ISSUE THREAD

**Issue by safil-badarudeen** [devvsakib/github-error-solve#58]
![image](https://user-images.githubusercontent.com/111175419/212995119-73d0f6e7-e78b-4e51-8761-56924d6fe6cc.png)

git commit -m ' commit message '  is this is how it supposed to display right? 
my text is not displaying in comment if i add <> this before and after commit message in  above line

**Comment by devvsakib** [comment]
hi, only use < lessthen sign....
ex
git add . < git commit -m "hh"< git push

**Comment by safil-badarudeen** [comment]
but git commit -m 'messsage' is showing in two lines and not showing < symbol , is it a bug  in data?

**Comment by devvsakib** [comment]
i fixed this this error @safil-badarudeen 
![image](https://user-images.githubusercontent.com/88339569/213103234-64f6098d-e6a3-48b8-acbb-3f8b70b258f0.png)

**Comment by safil-badarudeen** [comment]
Thank you,, does that error occured because of <> these  signs?

**Comment by devvsakib** [comment]
yes, if you look at this [ErrorSolutions](https://github.com/devvsakib/github-error-solve/blob/main/src/components/Error/ErrorSolutions.jsx) , we splited line by < this sign
![image](https://user-images.githubusercontent.com/88339569/213124472-36092192-a101-4872-9249-6b030bed0412.png)

**Comment by safil-badarudeen** [comment]
thank you. now i got it
