### ISSUE TITLE
cannot read description / read more less button

### ISSUE THREAD

**Issue by safil-badarudeen** [devvsakib/github-error-solve#59]
![image](https://user-images.githubusercontent.com/111175419/212996136-75c89739-dc15-47f9-a127-b761933c08a0.png)

If description is in multiple sentences , cannot read full description ,  I think if description is bigger than certain amount of alphabet we should have a Readmore/less button

**Comment by devvsakib** [comment]
thats an great idea @safil-badarudeen .  do you wannt to do this?

**Comment by safil-badarudeen** [comment]
Yes, i think I can implement this by utilising usestate hook, 

Should I need to have knowledge of vite to work with functionality  I am not familiar with that technology

**Comment by devvsakib** [comment]
@safil-badarudeen  no it's the same as create-react-app, vite just use jsx... nothing different

**Comment by safil-badarudeen** [comment]
@devvsakib  i have added show more/less button , colour is exactly same as description text colour , i thought people will know it is clickable when showing  showmore or less , let me know if needed to change colour of it,

**Comment by safil-badarudeen** [comment]
The bug that limited the lines of description were the line-clamp class from the tailwind , that also fixed.

**Comment by devvsakib** [comment]
Thank you Safil. Fixes #62 by @safil-badarudeen
