### ISSUE TITLE
hide scrollbar for all browser

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#61]
hide the scrollbar from the website
![image](https://user-images.githubusercontent.com/88339569/213199865-bdcc166b-a58f-4ff8-ab80-c219073f8472.png)

code you need:

body::-webkit-scrollbar {
  display: none;
}

html {
  overflow: auto;
  -ms-overflow-style: none;
  scrollbar-width: none;
}

**Comment by imtiazpy** [comment]
I think scrollbar is caused by the overflow of the Card content @devvsakib 

There is an issue #52 for the card content overflow issue. 
I will start working on it soon. 

If the overflow is identified for other issue then anybody can move forward with solving it..

**Comment by devvsakib** [comment]
sure thing @imtiazpy

**Comment by codemeop** [comment]
i can take this if you want

**Comment by devvsakib** [comment]
Closed as complete #66
