### ISSUE TITLE
[SUGGESTION]: we don't have any footer, do we need to add a footer?

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#75]
Currently, we don't have any footer on our website.
Do you think that we need to add a footer?

![image](https://user-images.githubusercontent.com/88339569/214061912-64d9732d-85bc-4c05-b7fa-2328c423992e.png)

**Comment by devvsakib** [comment]
yeah great idea, we can add github star too @safil-badarudeen

**Comment by safil-badarudeen** [comment]
yes that would be  great

**Comment by devvsakib** [comment]
want to take this? @safil-badarudeen

**Comment by safil-badarudeen** [comment]
Is react and tailwind knowledge enough for this work to be done? what does this vite do ? for testing?

**Comment by devvsakib** [comment]
nothing @safil-badarudeen . just create a footer components then import to Layout component.. thats it👌

**Comment by safil-badarudeen** [comment]
I will do it , if i have any doubts in between i will ask you .assign it
