### ISSUE TITLE
add contributors section to readme file

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#77]
add contributors section to readme file
![image](https://user-images.githubusercontent.com/88339569/214062672-51c39cbc-86d7-42de-9dad-eaa734cc5d31.png)

**Comment by MohamedAlDeep** [comment]
You mean the names in a table?

**Comment by devvsakib** [comment]
@MohamedAlDeep check this repository 
https://github.com/devvsakib/power-the-web

**Comment by MohamedAlDeep** [comment]
so the link of contributors https://github.com/devvsakib/github-error-solve/graphs/contributors
+
the image of them ?

**Comment by MohamedAlDeep** [comment]
Also do you mean to have contributors json file ? and those things (the above is included)

**Comment by MohamedAlDeep** [comment]
With the contributors page

**Comment by devvsakib** [comment]
@MohamedAlDeep  no need any JSON file, but if you want to do this, it will be plus

**Comment by MohamedAlDeep** [comment]
@devvsakib 
I can do it but for now i need the image of contributors or what do you think 
![image](https://user-images.githubusercontent.com/95958815/214089669-b972ed9f-fb9e-4117-9c35-68a2c66e2ff0.png)

**Comment by MohamedAlDeep** [comment]
@devvsakib can you assign me

**Comment by devvsakib** [comment]
lets do it @MohamedAlDeep

**Comment by devvsakib** [comment]
use this link for images https://contrib.rocks/image?repo=devvsakib/github-error-solve

**Comment by MohamedAlDeep** [comment]
@devvsakib i think all done

**Comment by MohamedAlDeep** [comment]
![image](https://user-images.githubusercontent.com/95958815/214121817-cad8e31a-6983-4aa9-91b5-1c8b41c3cd5b.png)

**Comment by MohamedAlDeep** [comment]
![image](https://user-images.githubusercontent.com/95958815/214121926-ad7da8f2-a6dd-488c-be8b-ab34c5b26e02.png)

**Comment by MohamedAlDeep** [comment]
responsive 
![image](https://user-images.githubusercontent.com/95958815/214122019-3a4d3f3b-cbac-46e6-a285-2f345c83df73.png)
also i dont know if this css is good for this but i just took the css of the others

**Comment by MohamedAlDeep** [comment]
![Uploading image.png…]()
hover

**Comment by MohamedAlDeep** [comment]
![image](https://user-images.githubusercontent.com/95958815/214122281-4e8e07eb-74de-4fa7-950b-5d5874ff8453.png)
hover

**Comment by MohamedAlDeep** [comment]
so i added json data

**Comment by MohamedAlDeep** [comment]
added header to contributions
![image](https://user-images.githubusercontent.com/95958815/214129469-4593c916-0f0c-47a2-8165-18e5fe9c59a0.png)

**Comment by devvsakib** [comment]
perfect, create an issue on creating contibutors page, I'll assign you @MohamedAlDeep

**Comment by devvsakib** [comment]
I raised an issue, you can comment there I'll assign you.
But make sure you make 2 PR. one for this issue and another for contrubutors page issue
