### ISSUE TITLE
add image to discord section of readme

### ISSUE THREAD

**Issue by Hrishi5111998** [devvsakib/github-error-solve#79]
unable to load image in discord section of **join us**  in the readme file please fix this issue!
![2023-01-23](https://user-images.githubusercontent.com/115489262/214091537-ec884715-c796-4879-9b85-2bf0c4f2080c.png)

**Comment by devvsakib** [comment]
anyone want to take this?

**Comment by rohinish404** [comment]
I can work on this..i have to add the discord image besides join us right?

**Comment by devvsakib** [comment]
use the image as link @rohinish404

**Comment by devvsakib** [comment]
assigned @rohinish404

**Comment by rohinish404** [comment]
can you give me the link to the discord so that i can add it there..which will redirect to discord on clicikng the discored icon.

**Comment by devvsakib** [comment]
link in readme file, please check @rohinish404

**Comment by rohinish404** [comment]
How it's looking? Also i couldn't find the link to your discord in the readme.
<img width="1435" alt="Screenshot 2023-01-24 at 1 33 42 AM" src="https://user-images.githubusercontent.com/92542124/214138623-09ed0ae1-e4f9-4000-bb14-918c69426744.png">

**Comment by devvsakib** [comment]
Looks better⚡
and I didn’t get it what do you mean. link is here at line 102
![IMG_20230124_021138.jpg](https://user-images.githubusercontent.com/88339569/214140054-31d56697-3858-4956-ade2-b43a39cc8a4a.jpg)

**Comment by devvsakib** [comment]
@rohinish404 you can make pr

**Comment by rohinish404** [comment]
> Looks better⚡ and I didn’t get it what do you mean. link is here at line 102 ![IMG_20230124_021138.jpg](https://user-images.githubusercontent.com/88339569/214140054-31d56697-3858-4956-ade2-b43a39cc8a4a.jpg)

oh my bad..i'll add the link and make a pr🙂

**Comment by devvsakib** [comment]
Completed #83

**Comment by Hrishi5111998** [comment]
looks great now
