### ISSUE TITLE
There should be a link to the github repo on the live site.

### ISSUE THREAD

**Issue by rohinish404** [devvsakib/github-error-solve#81]
I think there should be a link to the repo in the navbar(as there's no footer) besides docs on the live site.

**Comment by devvsakib** [comment]
wanna do this? @rohinish404

**Comment by rohinish404** [comment]
yeah sure!! Should i add a github icon besides docs which when clicked will redirect to the repo??

**Comment by devvsakib** [comment]
yeah perfect 🤝

**Comment by devvsakib** [comment]
are you able to add github star too? @rohinish404?

**Comment by rohinish404** [comment]
what's github star?

**Comment by devvsakib** [comment]
use this code snippet in header, it will show repository star
```html
<iframe src="https://ghbtns.com/github-btn.html?user=twbs&repo=bootstrap&type=star&count=true&size=large" frameborder="0" scrolling="0" width="170" height="30" title="GitHub"> </iframe>

```

**Comment by devvsakib** [comment]
add this code snippet to navbar, it will show repository star

```
<iframe src="https://ghbtns.com/github-btn.html?devvsakib=twbs&github-error-solve=bootstrap&type=star&count=true&size=large" frameborder="0" scrolling="0" width="170" height="30" title="GitHub"> </iframe>
```

**Comment by rohinish404** [comment]
> add this code snippet to navbar, it will show repository star
> 
> ```
> <iframe src="https://ghbtns.com/github-btn.html?devvsakib=twbs&github-error-solve=bootstrap&type=star&count=true&size=large" frameborder="0" scrolling="0" width="170" height="30" title="GitHub"> </iframe>
> ```

But then how will i add the link to the repo? when this link is clicked it it redirecting to a page showing 404 error.

**Comment by rohinish404** [comment]
I was thinking of adding a github icon like this👇 which will link to the repo.
<img width="1435" alt="Screenshot 2023-01-24 at 2 32 05 AM" src="https://user-images.githubusercontent.com/92542124/214149275-44eceab6-0971-43c3-881b-c38eb5a819a3.png">

**Comment by devvsakib** [comment]
wow, make a pr, no need to add repository star.. good job @rohinish404 👏🏻👏🏻

**Comment by rohinish404** [comment]
okay..thank you🙂

**Comment by devvsakib** [comment]
Completed #86
