### ISSUE TITLE
create CONTRIBUTORS page

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#82]
create a Contributors page and add to nabvar

**Comment by MohamedAlDeep** [comment]
@devvsakib it is done

**Comment by MohamedAlDeep** [comment]
in #77

**Comment by MohamedAlDeep** [comment]
oh never mind i didnt see the other comments

**Comment by devvsakib** [comment]
Assigned @MohamedAlDeep

**Comment by MohamedAlDeep** [comment]
@devvsakib i cant do 2 PRs i think

**Comment by MohamedAlDeep** [comment]
![image](https://user-images.githubusercontent.com/95958815/214143624-48f7e4c3-f612-4377-b518-57f76123e60a.png)

**Comment by devvsakib** [comment]
ok. make pr and add both issue in description🚀

**Comment by MohamedAlDeep** [comment]
alr

**Comment by devvsakib** [comment]
Closed #84
