### ISSUE TITLE
[BUG]: Image not showing in README

### ISSUE THREAD

**Issue by MohamedAlDeep** [devvsakib/github-error-solve#92]
**Describe the bug**
The image in contributors section is not showing, what is weird is that the link of the image is in the README but it is not rendering on the Github README preview. I dont know if that is only happening with me or it is also happening with you.

**To Reproduce**
1. Go to main [Github page](https://github.com/devvsakib/github-error-solve)
2. Scroll down 
3. look in the contributors section

**Expected behavior**
You should not see the image

**Screenshots**
![image](https://user-images.githubusercontent.com/95958815/214270198-975eccf9-e5fc-4c92-923a-8dc57bdb47e0.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [Windows 10]

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by devvsakib** [comment]
hmmm right, I have to take a look. thanks for raising issue
