### ISSUE TITLE
[HELP]: Add all contributors data into contributors.json

### ISSUE THREAD

**Issue by MohamedAlDeep** [devvsakib/github-error-solve#94]
just add all contributors to the data

**Comment by devvsakib** [comment]
maybe we can fetch all contributors by api

**Comment by MohamedAlDeep** [comment]
@devvsakib I am interested but i dont know how, can you recommend a tutorial for me

**Comment by MohamedAlDeep** [comment]
or wait i know fetch

**Comment by MohamedAlDeep** [comment]
just let me learn the api give me 30 mins

**Comment by devvsakib** [comment]
You need this API later ig,
here is the api https://api.github.com/repos/devvsakib/github-error-solve/contributors

**Comment by MohamedAlDeep** [comment]
@devvsakib thanks

**Comment by MohamedAlDeep** [comment]
@devvsakib Hello i did React-query for fetching but it doesnt work it gives me the error of route something about that 
and i tried to modify the route things but i get stuck tbh i dont know enough about route so currently i dont know how to do it

**Comment by devvsakib** [comment]
chill, I will do it, appreciate your effort. @MohamedAlDeep

**Comment by devvsakib** [comment]
I just figure out that we are able to fetch contributors but we are not able to get their Twitter handle🤔

**Comment by MohamedAlDeep** [comment]
@devvsakib it is not in the data right?
