### ISSUE TITLE
add this error solution

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/github-error-solve#95]
I found this random pic, if you know the correct solution to fix this, please add to `src/data/error.json` file.

![1674563506671.jpg](https://user-images.githubusercontent.com/88339569/214292488-cc452c8c-d6e7-4329-872a-15cd7a84fb1d.jpg)

**Comment by MohamedAlDeep** [comment]
Alr i found solution, assign me

**Comment by devvsakib** [comment]
Assigned 💪🏻
